### ISSUE TITLE
Email address on Contact page not hyperlinked

### ISSUE THREAD

**Issue by benotoho** [Abas-dev/the-a1uniforms#2]
The project specification requires that the email addresses shown on the website should launch a mail client (like Gmail, etc.) with a blank "Compose" page to send an email. Your emails on the Contact page and across the website do not do this.

You're supposed to have `<a href="mailto:xyz@xyz.com>` surrounding the email text.

**Comment by Abas-dev** [comment]
i will look into it

**Comment by Abas-dev** [comment]
the links have been set.

**Comment by benotoho** [comment]
It is not working. You didn't use the `mailto:` protocol. When the link is clicked, the site crashes.
