### ISSUE TITLE
No site map

### ISSUE THREAD

**Issue by benotoho** [Abas-dev/the-a1uniforms#3]
There is no site map, and this was a requirement. Check [here](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap) to learn about them. Your site map links in page footers should link to a `sitemap.xml` file in your root directory, instead of wrongfully linking to the Contact page.

**Comment by Abas-dev** [comment]
the site map has been added.

**Comment by benotoho** [comment]
It's not yet linked in the page footers.

**Comment by Abas-dev** [comment]
it has been properly linked
