### ISSUE TITLE
Contact page has only one address

### ISSUE THREAD

**Issue by benotoho** [Abas-dev/the-a1uniforms#4]
This is from your project specification:

> Contact Us page should also include the address and contact details of various outlets of A-1 uniforms in the city.

There is only one address on your Contact page.

**Comment by Abas-dev** [comment]
this has been taken care of.
Other address have been added to the Contact Us page.

**Comment by benotoho** [comment]
But there is still only one map for one of the addresses, instead of for 3 of them.
